module.exports = {
  Employee: {
    new_employee_button: '#page-header-desc-configuration-add',
    first_name_input: '#employee_firstname',
    last_name_input: '#employee_lastname',
    email_input: '#employee_email',
    password_input: '#employee_password',
    profile_select: '#employee_profile',
    save_button: '.btn-primary.float-right',
    orders_page: '#subtab-AdminParentOrders a',
    email_search_input: '[name=\'employee[email]\']',
    search_button_team: '[type=\'submit\'][name=\'employee[actions][search]\']',
    search_result: '.d-inline-block.card-header-title',
    team_employee_name: '#employee_grid tbody td:nth-child(3)',
    team_employee_last_name: '#employee_grid tbody td:nth-child(4)',
    team_employee_email: '#employee_grid tbody td:nth-child(5)',
    team_employee_profile: '#employee_grid tbody td:nth-child(6)',
    reset_search_button: '.btn.btn-link.js-reset-search.d-block.grid-reset-button',
    dropdown_toggle: '.btn.btn-link.dropdown-toggle.dropdown-toggle-dots.dropdown-toggle-split',
    delete_link: '#employee_filter_form .dropdown-menu-right.show',
    edit_button: '#table-employee a .edit',
    language_select: '#id_lang ',
    selected_language_option: '#id_lang option[selected="selected"]',
    employee_column_information: '#table-employee tr:nth-of-type(1) > td:nth-of-type(%COL)',
  }
};
